server:
  port: 8080
  servlet:
    context-path: "/bolderly"
app:
  swagger:
    host-name:
  bolderly:
    ignoringMatchers: /swagger-ui/**, /swagger-resources/**, /actuator/health, /v2/api-docs/**, /oauth/token
    jwt:
      aws:
        userPoolId: ${JWT_USER_POOL_ID:us-east-1_uIGGYZMeB}
        identityPoolId: ${JWT_IDENTITY_POOL_ID:us-east-1}
        jwkUrl: ${JWT_URL:}
        region: ${JWT_REGION:us-east-1}
        userNameField: ${JWT_USER_NAME_FIELD:cognito:username}
        connectionTimeout: ${JWT_CONNECTION_TIME_OUT:2000}
        readTimeout: ${JWT_READ_TIME_OUT:2000}
        httpHeader: ${JWT_HTTP_HEADER:Authorization}
        tokenuse: ${JWT_TOKEN_USE:access}
        clientId: ${JWT_CLIENT_ID:54r8juol3rr4pregbcfhr3i9ub}
        clientSecret: ${JWT_CLIENT_SECRET:1jki5n0eoc7klqdksv4bo1kqgthh09volbt17iak6q09oo0j9iuo}
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          token-uri: https://bolderly-oauth-dev.auth.us-east-1.amazoncognito.com/oauth2/token