server:
  port: 8080
  servlet:
    context-path: "/bolderly"
app:
  swagger:
    host-name:
  bolderly:
    ignoringMatchers: /swagger-ui/**, /swagger-resources/**, /actuator/health, /v2/api-docs/**, /token, /genKey, /encryptAndDecryptText/**, /encryptData, /client
    jwt:
      aws:
        userPoolId: ${JWT_USER_POOL_ID:ap-southeast-1_87DpLVK6G}
        identityPoolId: ${JWT_IDENTITY_POOL_ID:ap-southeast-1}
        jwkUrl: ${JWT_URL:}
        region: ${JWT_REGION:ap-southeast-1}
        userNameField: ${JWT_USER_NAME_FIELD:cognito:username}
        connectionTimeout: ${JWT_CONNECTION_TIME_OUT:2000}
        readTimeout: ${JWT_READ_TIME_OUT:2000}
        httpHeader: ${JWT_HTTP_HEADER:Authorization}
        tokenuse: ${JWT_TOKEN_USE:access}
    key:
      publicKey: publicKey.txt
      privateKey: privateKey.txt
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          user-name-attribute: cognito:username
          token-uri: https://bolderly.auth.ap-southeast-1.amazoncognito.com/oauth2/token
# Config Pool Size - Max Pool Size - Max queueCapacity
config:
  threadpool:
    corepool:
      size: 10
    maxpool:
      size: 100
    queueCapacity:
      size: 500