server:
  port: 8080
  servlet:
    context-path: "/martketplace-openservice/api"
app:
  swagger:
    host-name:
  service:
    ignoringMatchers: /swagger-ui/**, /swagger-resources/**, /actuator/health, /v2/api-docs/**, /v1/token, /v1/admin/encrypt, /v1/admin/client, /sForce/**
    jwt:
      aws:
        userPoolId: ${JWT_USER_POOL_ID:us-east-1_uIGGYZMeB}
        identityPoolId: ${JWT_IDENTITY_POOL_ID:us-east-1}
        jwkUrl: ${JWT_URL:}
        region: ${JWT_REGION:us-east-1}
        userNameField: ${JWT_USER_NAME_FIELD:cognito:username}
        connectionTimeout: ${JWT_CONNECTION_TIME_OUT:2000}
        readTimeout: ${JWT_READ_TIME_OUT:2000}
        httpHeader: ${JWT_HTTP_HEADER:Authorization}
        tokenuse: ${JWT_TOKEN_USE:access}
    sforce:
      http:
        connectTimeout: 30000
      client:
        provider:
          token-uri: https://advendio-programmatic-dev-ed.my.salesforce.com//services/oauth2/token
    cache:
      maximumSize: 1000
      initialCapacity: 32
      mins:
        expireAfterWrite: 3
      enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          user-name-attribute: cognito:username
          token-uri: https://bolderly-oauth-dev.auth.us-east-1.amazoncognito.com/oauth2/token
# Config Pool Size - Max Pool Size - Max queueCapacity
config:
  threadpool:
    corepool:
      size: 10
    maxpool:
      size: 100
    queueCapacity:
      size: 500

###### Variable System Info ####
clientID: ${CLIENT_ID}
keystore:
  path: ${KEYSTORE_PATH}
  alias: ${KEYSTORE_ALIAS}
  password: ${KEYSTORE_PASSWORD}
oauth:
  apiVersion: 51.0
  connecter:
    url: services/Soap/c/51.0
sandbox: true